dbinit.py
- Create GAMES table
- Delete dummy statement
- Format INIT_STATEMENTS to increase readability
=> Create games table

database.py, server.py, templates/game.html, templates/item_add.html, templates/item_add_result.html
- Modified database.py to handle adding an Item to the ITEMS table
- Modified server.py to render item adding page and result page
- Modified game.html to show admins an "Add item" button
- Created item_add.html to make it possible for an
admin to fill out a form for a given item's
attributes
- Created item_add_result to let the admin know that
the item they created has been added and made it
possible for them to go back to the game's page.
=> Add function to add items to a game (for admins)

database.py, server.py, templates/game.html
- Modified database.py to handle deleting an Item
from ITEMS table
- Modified server.py for the server to handle a delete
request
- Modified game.html so that admins can see
checkboxes next to Items and a delete button
underneath the Items
=> Add function to delete items (for admins)

database.py, dsn.txt, server.py
- Created Database class to decrease code repetition
and to introduce object orientation
- Cleaned some statements and declarations
=> Refactor database operations

server.py
It is updated in a way that each user may have one review for each game and may edit it.
=> add_review function updated

database.py
they are updated for handling time attributes of reviews. Also, get_reviews_of_game may query for user_id together with game_id now.
=> get_reviews_of_game and insert_review updated

database.py
Added in order to be able update an edited review.
=> update_review function added

database.py
It is updated in order to avoid from trying call fetchone() with empty cursor.
=> query_user_name updated for an error

server.py
function process_review_feedback is added in order to handle with AJAX requests of likes and dislikes.
new function of database.py get_prev_review took the place of get_reviews_of_game
=> Update for likes and dislikes of reviews

templates/game.html
added necessary forms
added path for script file
=> Updated for likes and dislikes of review

server.py
=> Fixed a bug in game_page

server.py
=> Fixed a bug

server.py
Screenshot additon and related changes added (Flask_upload library added, it must be installed)
=> Screenshot addition added

database.py
Added insert and get functions for screenshot
Fuctions of likes and dislikes are changed in order to use both reviews and screenshots
=> Changes related with screenshots

database.py
=> Bug is fixed

static/review_feedback.js
It was working properly with only the first review on the page. Now it is working properly.
=> Script improved

templates/game.html
They are changed according to review_feedback.js
=> Like and Dislike Forms improved

database.py
a function that deletes a review from reviews table according to game and user ids added.
=> Review deletion added

templates/game.html
If a review is written by the current user, current user is going to be able to see "Delete review" button.
=> "Delete review" button added

server.py
It was updated to delete also the related likes and dislikes
=> Review deletion updated

templates/game.html
Additional form elements review_id and game_id added as hidden inputs
=> Additional form element added for review deletion

server.py
The page that process deletion operation added
=> Screenshot deletion added

templates/game.html
Admin is able to delete any review or screenshot
=> Review and Screenshot deletion forms updated

templates/game.html
They are updated to work properly with timezone_handler.js
=> Addition dates diplay updated

server.py
process_review_feedback updated as process_likes_dislikes in order to handle all kind of likes and dislikes.
=> likes and dislikes process updated

static/review_feedback.js
Updated for handling all kind of likes and dislikes
=> Likes and dislikes handlers updated

server.py
Updated in order to make users be able to display other users' profile (without private informations of that user)
=> Profile function updated

server.py
Updated to make it compatible with new profile function. Also, code repeat is resolved by using redirect to profile funciton instead of using render template
=> Login function updated

database.py
In order to learn also the user name of the review
=> get_reviews_of_game query statement updated

database.py
In order to also learn game title and user name
=> get_screenhot updated

templates/profile.html
Add an if statement in profile.html. Add border to
table for visuality.
=> Show table in inventory only if the user has items

database.py, server.py, templates/profile.html
- profile.html: Users should be able to get
rid of their items. Add "Discard item" button.
- server.py: Add "GET" and "POST" methods. If the
user presses the "Discard item" button, get the
item_id and delete it from ITEMS_OF_USERS table
for that user.
- database.py: Add "delete_item_from_user" function
=> Add ability to get rid of items

database.py, server.py, templates/screenshot.html, templates/screenshot_comment_edit.html, templates/screenshot_comment_edit_result.html
- screenshot.html: Add "Edit" link under comment for
each user.
- database.py: Add "update_screenshot_comment" function.
- server.py: Sort comments by comment_id. Delete
"screenshot_comments_page". Add "screenshot_comment_edit_page" and
"screenshot_comment_edit_result_page".
=> Add ability to edit comments

database.py
=> get_screenshots_of_game updated
